services:
  valhalla:
    image: ghcr.io/valhalla/valhalla:latest
    container_name: valhalla
    ports:
      - "8002:8002"
    volumes:
      - ./data:/data
    environment:
      - tile_urls=
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      valhalla_build_tiles -c /data/valhalla.json /data/russia.osm.pbf &&
      valhalla_service /data/valhalla.json 1
      "